### ISSUE TITLE
MACE-LAMMPS meta issue

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/mace#278]
I need a place to organize/triage some LAMMPS-related issues.

- [ ] better tests for different architectures!
- [ ] need to document multi-GPU https://github.com/ACEsuit/mace/discussions/274
- [ ] this PR needs merging https://github.com/ACEsuit/lammps/pull/1 (and related https://github.com/ACEsuit/mace/issues/195#issuecomment-1838942935)
- [ ] need to tidy/improve single-precision support for Kokkos https://github.com/ACEsuit/mace/discussions/274
- [ ] need per-atom energies in Kokkos mode https://github.com/ACEsuit/mace/issues/193
- [ ] a request for per-atom virials https://github.com/ACEsuit/mace/discussions/272
- [ ] investigate `Kokkos::parallel_scan` to tidy the Kokkos code (suggested by Anders Johansson)
- [ ] refactor the MPI splitting using something like `MPI_COMM_WORLD_rank % n_gpus_per_node` (suggested by @bernstei)
- [ ] request for plug-in mode (need to think about this one) https://github.com/ACEsuit/mace/issues/271

**Comment by ilyes319** [comment]
Excellent idea, thank you!
